routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('psDashboard');

Route::middleware('not.authenticated.user')->group(function(){
	Route::get('register', 'Auth\RegisterController@create')->name('psUserRegistration');
	Route::post('register', 'Auth\RegisterController@store')->name('psUserRegistrationPost');

	Route::get('login', 'Auth\LoginController@index')->name('psUserLogin');
	Route::post('authenticate', 'Auth\LoginController@authenticate')->name('psUserLoginAuthenticate');
	Route::get('logout', 'Auth\LoginController@logout')->name('psUserLogout');

	Route::get('login/forgot', 'Auth\ResetPasswordController@create')->name('psResetPassword');
	Route::post('login/forgot', 'Auth\ResetPasswordController@store')->name('psResetPasswordPost');
});

Route::prefix('support')->group(function(){
	Route::get('policies.html', 'Support\PoliciesController@index')->name('psSupportPolicies');
	Route::get('privacy.html', 'Support\PrivacyController@index')->name('psSupportPrivacy');
	Route::get('shipping.html', 'Support\ShippingController@index')->name('psSupportShipping');
	Route::get('returns.html', 'Support\ReturnsAndExchangesController@index')->name('psSupportReturnsAndExchanges');
	Route::get('contact.html', 'Support\ContactUsController@index')->name('psSupportContactUs');
	Route::post('contact.html', 'Support\ContactUsController@send')->name('psSupportContactUsSend');
	Route::get('faq.html', 'Support\FAQController@index')->name('psSupportFAQ');
});

Route::prefix('about')->group(function(){
	Route::get('scholarship.html', 'About\ScholarshipController@index')->name('psAboutScholarship');
	Route::post('scholarship.html', 'About\ScholarshipController@store')->name('psAboutScholarshipPost');
	Route::get('scholarship-winners.html', 'About\ScholarshipController@winners')->name('psAboutScholarshipWinner');

	Route::get('careers.html', 'About\CareersController@index')->name('psCareers');
	Route::post('careers.html', 'About\CareersController@store')->name('psCareersPost');

	Route::get('team.html', 'About\TeamController@index')->name('psTeam');
	Route::get('reviews.html', 'About\ReviewsController@index')->name('psReviews');

	Route::post('newsletter', 'CMS\NewsletterController@store')->name('psNewsletter');
});

Route::get('how-to-plumb.html', 'CMS\HowToPlumbController@index')->name('psHowToPlumb');
Route::get('how-to-hvac.html', 'CMS\HowToHVACController@index')->name('psHowToHVAC');
Route::get('how-to-sprinklers.html', 'CMS\HowToSprinklersController@index')->name('psHowToSprinklers');

Route::get('account', 'Account\AccountController@index')->middleware('authenticated.user')->name('psAccount');
Route::prefix('account')->middleware('authenticated.user')->group(function(){
	Route::resource('info', 'Account\InfoController')->only(['index', 'edit', 'update']);
	Route::resource('login', 'Account\LoginInfoController')->only(['edit', 'update']);
	Route::resource('address-book', 'Account\AddressBookController');

	Route::resource('shopping', 'Account\ShoppingListController')->only(['index', 'create', 'store', 'show']);
	Route::get('subscriptions', 'Account\SubscriptionsController@index')->name('psAccountSubscriptions');
	#Route::resource('book', 'Account\AddressBookController')->only(['index', 'create', 'store']);

	Route::prefix('orders')->group(function(){
		Route::get('/', 'Account\OrdersController@index')->name('psAccountOrders');
		Route::get('{order_id}/tracking', 'Account\OrderTrackingController@show')->name('psAccountOrdersTracking');
		Route::get('{order_id}/print', 'Account\OrdersController@show')->name('psAccountOrdersPrint');
		
		Route::get('{order_id}/cancel', 'Account\OrderCancelController@index')->name('psOrderCancel');
		Route::put('{order_id}/cancel', 'Account\OrderCancelController@update')->name('psOrderCancelPut');

		Route::resource('return', 'Account\OrderReturnController')->only(['index', 'store']);
	});
});

Route::get('cart.html', 'Account\CartController@index')->name('psCart');
Route::post('cart.html/store', 'Account\CartController@store')->name('psCartStore');
Route::delete('cart.html/{key}', 'Account\CartController@destroy')->name('psCartDelete');

Route::resource('questions-and-answer', 'Catalog\ProductQuestionAndAnswerController');
Route::post('reviews/store', 'Catalog\ProductReviewController@store')->middleware('web')->name('psProductReviewStore');

Route::get('/{slug?}', 'Catalog\ProductPageController@index')->where('slug', '.+')->middleware('web')->name('psProductPage');

resources/views/partials/account-sidebar.blade.php
<h6 class="text-center">My Account</h6>
<ul class="accordion accordion-account" data-accordion data-allow-all-closed="true">
	<li class="accordion-item" data-accordion-item>
		<a href="#" class="accordion-title">My Orders</a>
		<div class="accordion-content" data-tab-content>
			<a href="{{ route('psCart') }}">My Shopping Cart</a><br/>
			<a href="{{ route('psAccountOrders') }}">My Order History</a><br/>
		</div>
	</li>
	<li class="accordion-item" data-accordion-item>
		<a href="#" class="accordion-title">My Wist Lists</a>
		<div class="accordion-content" data-tab-content>
			<a href="{{ route('shopping.index') }}">My Wish Lists</a><br/>
			<a href="{{ route('shopping.create') }}">Create New List</a><br/>
		</div>
	</li>
	<li class="accordion-item" data-accordion-item>
		<a href="#" class="accordion-title">My Account</a>
		<div class="accordion-content" data-tab-content>
			<a href="{{ route('psAccount') }}">My Dashboard</a><br/>
			<a href="{{ route('info.index') }}">My Information</a><br/>
			<a href="{{ route('psAccountSubscriptions') }}">My Subscriptions</a><br/>
		</div>
	</li>
	<li class="accordion-item" data-accordion-item>
		<a href="#" class="accordion-title">My Address Book</a>
		<div class="accordion-content" data-tab-content>
			<a href="{{ route('address-book.index') }}">My Address Book</a><br/>
			<a href="{{ route('address-book.create') }}">Create New Address</a><br/>
		</div>
	</li>
</ul>

resources/views/partials/error-messages.blade.php
@if($errors->any())
<div class="callout warning">
	<ul>
		@foreach($errors->all() as $error)
		<li>{{ $error }}</li>
		@endforeach
	</ul>
</div>
@elseif(session('custom_error'))
<div class="callout warning">
	{{ session('custom_error') }}
</div>
@elseif(session('success_msg'))
<div class="callout success">
	{{ session('success_msg') }}
</div>
@endif

resources/views/partials/footer.blade.php
		<div class="callout small callout-footer margin-top-custom-50">
			<div class="container grid-x footer-wrapper">

				<div class="cell large-2 medium-4 small-12">
					<strong>Policies</strong>
					<ul class="menu vertical">
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Shipping Policy</a></li>
						<li><a href="#">Returns & Exchanges</a></li>
					</ul>
				</div>

				<div class="cell large-2 medium-4 small-12">
					<strong>Customer Service</strong>
					<ul class="menu vertical">
						<li><a href="#">Contact Us</a></li>
						<li><a href="#">Scholarship Opportunity</a></li>
						<li><a href="#">Frequently Asked Questions</a></li>
					</ul>
				</div>

				<div class="cell large-2 medium-4 small-12">
					<strong>How-To Guides</strong>
					<ul class="menu vertical">
						<li><a href="#">Plumbing Tutorials</a></li>
						<li><a href="#">HVAC Tutorials</a></li>
						<li><a href="#">Sprinkler Tutorials</a></li>
					</ul>
				</div>

				<div class="cell large-2 medium-4 small-12">
					<strong>My Account</strong>
					<ul class="menu vertical">
						<li><a href="#">Order History</a></li>
						<li><a href="#">Account Information</a></li>
						<li><a href="#">My Shopping Lists</a></li>
					</ul>
				</div>

				<div class="cell large-2 medium-4 small-12">
					<strong>PlumbersStock</strong>
					<ul class="menu vertical">
						<li><a href="#">Careers</a></li>
						<li><a href="#">About Us</a></li>
						<li><a href="#">Our Blog</a></li>
						<li><a href="#">Reviews</a></li>
					</ul>
				</div>

				<div class="cell large-2 medium-4 small-12">
					<strong>Newsletter Sign-up</strong>
					<form id="newsletter-sign-up">
						<div class="input-group">
							<input type="text" name="" class="input-group-field radius-left" />
							<div class="input-group-button">
								<button type="submit" class="button small success radius-right" style="background-color: #5cb85c;">Sign Up!</button>
							</div>
						</div>
					</form>
				</div>

			</div>
		</div>
		<div class="container">
			<div class="grid-x site-badge margin-top-custom-40">
				<div class="cell large-2 medium-3 small-12">
					<a href="https://www.shopperapproved.com/reviews/PlumbersStock.com/" class="shopperlink"><img src="https://c813008.ssl.cf2.rackcdn.com/23883-med.png" style="border: 0" alt="Shopper Award" oncontextmenu="var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by shopperapproved \251 '+d.getFullYear()+'.'); return false;" /></a><script type="text/javascript">(function() { var js = window.document.createElement("script"); js.src = '//www.shopperapproved.com/seals/certificate.js'; js.type = "text/javascript"; document.getElementsByTagName("head")[0].appendChild(js); })();</script><br>
				</div>
				<div class="cell large-2 medium-3 small-12">
					<span id="siteseal">
						<script async type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=0sHydqExr9LzZpDisP3MQD2aJV1pqoi3djSvP3PiXGVruM6xRdiFQFusmob6"></script>
					</span><br>
				</div>
				<div class="cell large-2 medium-3 small-12">
					<div id="GTS_CONTAINER" style="dispay:inline-table; margin:0 30px;"></div><br>
				</div>
				<div class="cell large-2 medium-3 small-12">
					<a href="https://www.resellerratings.com" onclick="window.open('https://seals.resellerratings.com/landing.php?seller=24302','name','height=760,width=780,scrollbars=1');return false;">
						<img style='border:none;' src='//seals.resellerratings.com/seal.php?seller=24302' oncontextmenu="alert('Copying Prohibited by Law - ResellerRatings seal is a Trademark of Answers.com'); return false;" />
					</a><br>
				</div>
			</div>
			<p class="ps-copy-rights text-center margin-top-custom-40">
				Copyright &copy; 2007 - 2019 <strong class="footer-dot">.</strong> PlumbersStock 
				<span class="footer-terms-of-use"><a href="">Term of Use</a> <strong class="footer-dot">.</strong> <a href="">All Categories</a></span>
			</p>
		</div>

resources/views/partials/main-menu.blade.php
<?php
$mainmenu_key = request()->server('HTTP_HOST').':mainmenu:'.request()->server('REQUEST_SCHEME');
if (Illuminate\Support\Facades\Redis::exists($mainmenu_key)) {
	echo Illuminate\Support\Facades\Redis::get($mainmenu_key);
}

?>

resources/views/partials/select-country.blade.php
<option value="">Please Select A Country</option>
<option value="US">United States</option>
<option value="CA">Canada</option>

<option value="" disabled>━━━━━━━━━━━━</option>

<option value="AF">Afghanistan</option>
<option value="AX">Åland Islands</option>
<option value="AL">Albania</option>
<option value="DZ">Algeria</option>
<option value="AS">American Samoa</option>
<option value="AD">Andorra</option>
<option value="AO">Angola</option>
<option value="AI">Anguilla</option> 
<option value="AQ">Antarctica</option>
<option value="AG">Antigua and Barbuda</option>
<option value="AR">Argentina</option>
<option value="AM">Armenia</option>
<option value="AW">Aruba</option>
<option value="AU">Australia</option>
<option value="AT">Austria</option>
<option value="AZ">Azerbaijan</option>
<option value="BS">Bahamas</option>
<option value="BH">Bahrain</option>
<option value="BD">Bangladesh</option>
<option value="BB">Barbados</option>
<option value="BY">Belarus</option>
<option value="BE">Belgium</option>
<option value="BZ">Belize</option>
<option value="BJ">Benin</option>
<option value="BM">Bermuda</option>
<option value="BT">Bhutan</option>
<option value="BO">Bolivia</option>
<option value="BA">Bosnia and Herzegovina</option>
<option value="BW">Botswana</option>
<option value="BV">Bouvet Island</option>
<option value="BR">Brazil</option>
<option value="IO">British Indian Ocean Territory</option>
<option value="BN">Brunei Darussalam</option>
<option value="BG">Bulgaria</option>
<option value="BF">Burkina Faso</option>
<option value="BI">Burundi</option>
<option value="KH">Cambodia</option>
<option value="CM">Cameroon</option>
<!--<option value="CA">Canada</option>-->
<option value="CV">Cape Verde</option>
<option value="KY">Cayman Islands</option>
<option value="CF">Central African Republic</option>
<option value="TD">Chad</option>
<option value="CL">Chile</option>
<option value="CN">China</option>
<option value="CX">Christmas Island</option>
<option value="CC">Cocos (Keeling) Islands</option>
<option value="CO">Colombia</option>
<option value="KM">Comoros</option>
<option value="CG">Congo</option>
<option value="CD">Congo, The Democratic Republic of The</option>
<option value="CK">Cook Islands</option>
<option value="CR">Costa Rica</option>
<option value="CI">Cote D'ivoire</option>
<option value="HR">Croatia</option>
<option value="CU">Cuba</option>
<option value="CY">Cyprus</option>
<option value="CZ">Czech Republic</option>
<option value="DK">Denmark</option>
<option value="DJ">Djibouti</option>
<option value="DM">Dominica</option>
<option value="DO">Dominican Republic</option>
<option value="EC">Ecuador</option>
<option value="EG">Egypt</option>
<option value="SV">El Salvador</option>
<option value="GQ">Equatorial Guinea</option>
<option value="ER">Eritrea</option>
<option value="EE">Estonia</option>
<option value="ET">Ethiopia</option>
<option value="FK">Falkland Islands (Malvinas)</option>
<option value="FO">Faroe Islands</option>
<option value="FJ">Fiji</option>
<option value="FI">Finland</option>
<option value="FR">France</option>
<option value="GF">French Guiana</option>
<option value="PF">French Polynesia</option>
<option value="TF">French Southern Territories</option>
<option value="GA">Gabon</option>
<option value="GM">Gambia</option>
<option value="GE">Georgia</option>
<option value="DE">Germany</option>
<option value="GH">Ghana</option>
<option value="GI">Gibraltar</option>
<option value="GR">Greece</option>
<option value="GL">Greenland</option>
<option value="GD">Grenada</option>
<option value="GP">Guadeloupe</option>
<option value="GU">Guam</option>
<option value="GT">Guatemala</option>
<option value="GG">Guernsey</option>
<option value="GN">Guinea</option>
<option value="GW">Guinea-bissau</option>
<option value="GY">Guyana</option>
<option value="HT">Haiti</option>
<option value="HM">Heard Island and Mcdonald Islands</option>
<option value="VA">Holy See (Vatican City State)</option>
<option value="HN">Honduras</option>
<option value="HK">Hong Kong</option>
<option value="HU">Hungary</option>
<option value="IS">Iceland</option>
<option value="IN">India</option>
<option value="ID">Indonesia</option>
<option value="IR">Iran, Islamic Republic of</option>
<option value="IQ">Iraq</option>
<option value="IE">Ireland</option>
<option value="IM">Isle of Man</option>
<option value="IL">Israel</option>
<option value="IT">Italy</option>
<option value="JM">Jamaica</option>
<option value="JP">Japan</option>
<option value="JE">Jersey</option>
<option value="JO">Jordan</option>
<option value="KZ">Kazakhstan</option>
<option value="KE">Kenya</option>
<option value="KI">Kiribati</option>
<option value="KP">Korea, Democratic People's Republic of</option>
<option value="KR">Korea, Republic of</option>
<option value="KW">Kuwait</option>
<option value="KG">Kyrgyzstan</option>
<option value="LA">Lao People's Democratic Republic</option>
<option value="LV">Latvia</option>
<option value="LB">Lebanon</option>
<option value="LS">Lesotho</option>
<option value="LR">Liberia</option>
<option value="LY">Libyan Arab Jamahiriya</option>
<option value="LI">Liechtenstein</option>
<option value="LT">Lithuania</option>
<option value="LU">Luxembourg</option>
<option value="MO">Macao</option>
<option value="MK">Macedonia, The Former Yugoslav Republic of</option>
<option value="MG">Madagascar</option>
<option value="MW">Malawi</option>
<option value="MY">Malaysia</option>
<option value="MV">Maldives</option>
<option value="ML">Mali</option>
<option value="MT">Malta</option>
<option value="MH">Marshall Islands</option>
<option value="MQ">Martinique</option>
<option value="MR">Mauritania</option>
<option value="MU">Mauritius</option>
<option value="YT">Mayotte</option>
<option value="MX">Mexico</option>
<option value="FM">Micronesia, Federated States of</option>
<option value="MD">Moldova, Republic of</option>
<option value="MC">Monaco</option>
<option value="MN">Mongolia</option>
<option value="ME">Montenegro</option>
<option value="MS">Montserrat</option>
<option value="MA">Morocco</option>
<option value="MZ">Mozambique</option>
<option value="MM">Myanmar</option>
<option value="NA">Namibia</option>
<option value="NR">Nauru</option>
<option value="NP">Nepal</option>
<option value="NL">Netherlands</option>
<option value="AN">Netherlands Antilles</option>
<option value="NC">New Caledonia</option>
<option value="NZ">New Zealand</option>
<option value="NI">Nicaragua</option>
<option value="NE">Niger</option>
<option value="NG">Nigeria</option>
<option value="NU">Niue</option>
<option value="NF">Norfolk Island</option>
<option value="MP">Northern Mariana Islands</option>
<option value="NO">Norway</option>
<option value="OM">Oman</option>
<option value="PK">Pakistan</option>
<option value="PW">Palau</option>
<option value="PS">Palestinian Territory, Occupied</option>
<option value="PA">Panama</option>
<option value="PG">Papua New Guinea</option>
<option value="PY">Paraguay</option>
<option value="PE">Peru</option>
<option value="PH">Philippines</option>
<option value="PN">Pitcairn</option>
<option value="PL">Poland</option>
<option value="PT">Portugal</option>
<option value="PR">Puerto Rico</option>
<option value="QA">Qatar</option>
<option value="RE">Reunion</option>
<option value="RO">Romania</option>
<option value="RU">Russian Federation</option>
<option value="RW">Rwanda</option>
<option value="SH">Saint Helena</option>
<option value="KN">Saint Kitts and Nevis</option>
<option value="LC">Saint Lucia</option>
<option value="PM">Saint Pierre and Miquelon</option>
<option value="VC">Saint Vincent and The Grenadines</option>
<option value="WS">Samoa</option>
<option value="SM">San Marino</option>
<option value="ST">Sao Tome and Principe</option>
<option value="SA">Saudi Arabia</option>
<option value="SN">Senegal</option>
<option value="RS">Serbia</option>
<option value="SC">Seychelles</option>
<option value="SL">Sierra Leone</option>
<option value="SG">Singapore</option>
<option value="SK">Slovakia</option>
<option value="SI">Slovenia</option>
<option value="SB">Solomon Islands</option>
<option value="SO">Somalia</option>
<option value="ZA">South Africa</option>
<option value="GS">South Georgia and The South Sandwich Islands</option>
<option value="ES">Spain</option>
<option value="LK">Sri Lanka</option>
<option value="SD">Sudan</option>
<option value="SR">Suriname</option>
<option value="SJ">Svalbard and Jan Mayen</option>
<option value="SZ">Swaziland</option>
<option value="SE">Sweden</option>
<option value="CH">Switzerland</option>
<option value="SY">Syrian Arab Republic</option>
<option value="TW">Taiwan, Province of China</option>
<option value="TJ">Tajikistan</option>
<option value="TZ">Tanzania, United Republic of</option>
<option value="TH">Thailand</option>
<option value="TL">Timor-leste</option>
<option value="TG">Togo</option>
<option value="TK">Tokelau</option>
<option value="TO">Tonga</option>
<option value="TT">Trinidad and Tobago</option>
<option value="TN">Tunisia</option>
<option value="TR">Turkey</option>
<option value="TM">Turkmenistan</option>
<option value="TC">Turks and Caicos Islands</option>
<option value="TV">Tuvalu</option>
<option value="UG">Uganda</option>
<option value="UA">Ukraine</option>
<option value="AE">United Arab Emirates</option>
<option value="GB">United Kingdom</option>
<!--<option value="US">United States</option>-->
<option value="UM">United States Minor Outlying Islands</option>
<option value="UY">Uruguay</option>
<option value="UZ">Uzbekistan</option>
<option value="VU">Vanuatu</option>
<option value="VE">Venezuela</option>
<option value="VN">Viet Nam</option>
<option value="VG">Virgin Islands, British</option>
<option value="VI">Virgin Islands, U.S.</option>
<option value="WF">Wallis and Futuna</option>
<option value="EH">Western Sahara</option>
<option value="YE">Yemen</option>
<option value="ZM">Zambia</option>
<option value="ZW">Zimbabwe</option>

resources/views/partials/select-state.blade.php
<option value="">Please Select A State</option>
<option value="AL">Alabama</option>
<option value="AK">Alaska</option>
<option value="AZ">Arizona</option>
<option value="AR">Arkansas</option>
<option value="CA">California</option>
<option value="CO">Colorado</option>
<option value="CT">Connecticut</option>
<option value="DE">Delaware</option>
<option value="FL">Florida</option>
<option value="GA">Georgia</option>
<option value="HI">Hawaii</option>
<option value="ID">Idaho</option>
<option value="IL">Illinois</option>
<option value="IN">Indiana</option>
<option value="IA">Iowa</option>
<option value="KS">Kansas</option>
<option value="KY">Kentucky</option>
<option value="LA">Louisiana</option>
<option value="ME">Maine</option> 
<option value="MD">Maryland</option>
<option value="MA">Massachusetts</option>
<option value="MI">Michigan</option>
<option value="MN">Minnesota</option>
<option value="MS">Mississippi</option>
<option value="MO">Missouri</option>
<option value="MT">Montana</option>
<option value="NE">Nebraska</option>
<option value="NV">Nevada</option>
<option value="NH">New Hampshire</option>
<option value="NJ">New Jersey</option>
<option value="NM">New Mexico</option>
<option value="NY">New York</option>
<option value="NC">North Carolina</option>
<option value="ND">North Dakota</option>
<option value="OH">Ohio</option>
<option value="OK">Oklahoma</option>
<option value="OR">Oregon</option>
<option value="PA">Pennsylvania</option>
<option value="RI">Rhode Island</option>
<option value="SC">South Carolina</option>
<option value="SD">South Dakota</option>
<option value="TN">Tennessee</option>
<option value="TX">Texas</option>
<option value="UT">Utah</option>
<option value="VT">Vermont</option>
<option value="VA">Virginia</option>
<option value="WA">Washington</option>
<option value="WV">West Virginia</option>
<option value="WI">Wisconsin</option>
<option value="WY">Wyoming</option>
<option value="" disabled>━━━━━━━━━━━━</option>
<option value="DC">Washington, D.C.</option>
<option value="" disabled>━━━━━━━━━━━━</option>
<option value="AS">American Samoa</option>
<option value="GU">Guam</option>
<option value="MP">Northern Mariana Islands</option>
<option value="PR">Puerto Rico</option>
<option value="VI">U.S. Virgin Islands</option>

resources/views/partials/success-message.blade.php
@if(session('success_message'))
<div class="callout success text-center">{!! session('success_message') !!}</div>
@elseif(session('custom_error'))
<div class="callout warning text-center">{!! session('custom_error') !!}</div>
@endif